version: "3.9"

services:
  postgres:
    container_name: telework-reservation-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teleworkreservations
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres:/var/lib/postgresql/data/
    restart: unless-stopped